REQUEST:
  FILE: None
  CONSTRAINTS:
    max_assign_time: 600
    max_pickup_time: 600
    max_travel_time_mul: 1.5
    max_travel_dis_mul: 1.5
  BEHAVIORS:
    max_assign_time: 600
    max_pickup_time: 600
    cancel_prob_assign: 0.6
    cancel_prob_pickup: 0.1
    max_tol_vehicle_capacity: 4
    max_tol_price: 0

VEHICLE:
  FILE: None
  NUM: 1000
  REPOSITION: False

ENVIRONMENT:
  TYPE: 'toy'
  FILE: None
  CONSIDER_ITINERARY: True